# Generated by Django 6.0.5 on 2026-05-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplevoucher',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examplevoucher',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
