# Generated by Django 6.0.5 on 2026-08-02 18:36

import django.db.models.deletion
from django.db import migrations, models


def backfill_remaining_value(apps, schema_editor):
    ExampleVoucher = apps.get_model('vouchers', 'ExampleVoucher')
    ExampleVoucher.objects.filter(remaining_value__isnull=True).update(remaining_value=models.F('value'))


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_examplevoucher_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplevoucher',
            name='remaining_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.RunPython(backfill_remaining_value, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='examplevoucher',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='vouchers.examplevoucher')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
